<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="snd_robot">

        <gazebo>
            <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>20</updateRate>
                <leftJoint>left_wheel_joint</leftJoint>
                <rightJoint>right_wheel_joint</rightJoint>
                <wheelSeparation>${motor_wheel_separation}</wheelSeparation>
                <wheelAcceleration>0</wheelAcceleration>
                <wheelTorque>5</wheelTorque>
                <wheelDiameter>${2.0 * motor_wheel_radius}</wheelDiameter>
                <torque>20</torque>
                <commandTopic>cmd_vel</commandTopic>
                <odometryTopic>odom</odometryTopic>
                <odometryFrame>odom</odometryFrame>
                <odometrySource>1</odometrySource>
                <robotBaseFrame>base_link</robotBaseFrame>
                <legacyMode>false</legacyMode>
                <publishTf>true</publishTf>
                <publishWheelTF>true</publishWheelTF>
                <publishWheelJointState>true</publishWheelJointState>
                <rosDebugLevel>0</rosDebugLevel>
            </plugin>
        </gazebo>

</robot>
