<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="snd_robot">
    <xacro:include filename="$(find snd_description)/urdf/macros.xacro"/>

    <xacro:property name="motor_wheel_radius" value="0.0355"/>
    <xacro:property name="motor_wheel_width" value="0.011"/>
    <xacro:property name="motor_wheel_separation" value="0.23"/>
    <xacro:property name="body_length" value="0.23"/>
    <xacro:property name="body_width" value="0.265"/>
    <xacro:property name="body_height" value="0.32"/>
    <!-- distance between floor and base of robot body -->
    <xacro:property name="robot_clearance" value="0.010"/>
    <xacro:property name="robot_weight" value="4.0"/>
    <xacro:property name="caster_radius" value="0.005"/>
    <xacro:property name="beacon_mast_height" value="0.095"/>
    <xacro:property name="beacon_mast_radius" value="0.050"/>

    <material name="dark_grey">
        <color rgba="0.2 0.2 0.2 1"/>
    </material>
    <material name="light_grey">
        <color rgba="0.8 0.8 0.8 0.8"/>
    </material>
    <material name="beige">
        <color rgba="0.76 0.76 0.7 1.0"/>
    </material>
    <material name="blue">
        <color rgba="0.0 0.0 0.7 1.0"/>
    </material>

    <xacro:macro name="robot_body">
        <link name="base_link"></link>

        <link name="robot_body">
            <visual>
                <orign xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${body_length} ${body_width} ${body_height}"/>
                </geometry>
                <material name="light_grey"/>
            </visual>
            <collision>
                <orign xyz="0.0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${body_length} ${body_width} ${body_height}"/>
                </geometry>
            </collision>
            <inertial>
                <orign xyz="0.0 0 0" rpy="0 0 0"/>
                <mass value="${robot_weight}"/>
                <xacro:box_inertia m="${robot_weight}" x="${body_length}" y="${body_width}" z="${body_height}"/>
            </inertial>
        </link>
        <joint name="base_to_body" type="fixed">
            <parent link="base_link"/>
            <child link="robot_body"/>
            <origin xyz="0 0 ${body_height/2 + robot_clearance}" rpy="0 0 0"/>
        </joint>

        <link name="beacon_mast">
            <visual>
                <orign xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${beacon_mast_height}" radius="${beacon_mast_radius}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <orign xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${beacon_mast_height}" radius="${beacon_mast_radius}"/>
                </geometry>
                <material name="blue"/>
            </collision>
            <inertial>
                <orign xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.01"/>
                <xacro:cylinder_inertia m="0.1" r="${motor_wheel_radius}" h="${motor_wheel_width}"/>
            </inertial>
        </link>
        <joint name="mast_to_body" type="fixed">
            <parent link="base_link"/>
            <child link="beacon_mast"/>
            <origin xyz="0 0 ${body_height + robot_clearance + beacon_mast_height / 2}" rpy="0 0 0"/>
        </joint>

        <xacro:macro name="wheel" params="prefix ypos dir">
            <link name="${prefix}_wheel">
                <visual>
                    <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
                    <geometry>
                        <cylinder length="${motor_wheel_width}" radius="${motor_wheel_radius}"/>
                    </geometry>
                    <material name="blue"/>
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
                    <geometry>
                        <cylinder length="${motor_wheel_width}" radius="${motor_wheel_radius}"/>
                    </geometry>
                </collision>
                <inertial>
                    <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
                    <mass value="0.1"/>
                    <xacro:cylinder_inertia m="0.1" r="${motor_wheel_radius}" h="${motor_wheel_width}"/>
                </inertial>
            </link>
            <joint name="${prefix}_wheel_joint" type="continuous">
                <parent link="base_link"/>
                <child link="${prefix}_wheel"/>
                <origin xyz="0 ${ypos} ${motor_wheel_radius}" rpy="0 0 ${dir * pi/2}"/>
                <axis xyz="${dir} 0 0"/>
            </joint>
            <transmission name="${prefix}_wheel_trans">
                <type>transmission_interface/SimpleTransmission</type>
                <joint name="${prefix}_wheel_joint">
                    <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                </joint>
                <actuator name="${prefix}_wheel_actuator">
                    <mechanicalReduction>1</mechanicalReduction>
                </actuator>
            </transmission>

            <gazebo reference="${prefix}_wheel">
                <mu1 value="1.0"/>
                <mu2 value="1.0"/>
            </gazebo>
        </xacro:macro>
        <xacro:wheel prefix="left"  ypos="${motor_wheel_separation / 2.0}" dir="1"/>
        <xacro:wheel prefix="right" ypos="-${motor_wheel_separation / 2.0}" dir="-1"/>

        <xacro:macro name="caster" params="prefix position">
            <link name="${prefix}_caster">
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <sphere radius="${caster_radius}"/>
                    </geometry>
                    <material name="dark_grey"/>
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <sphere radius="${caster_radius}"/>
                    </geometry>
                </collision>
                <inertial>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <mass value="0.05"/>
                    <xacro:sphere_inertia m="0.05" r="${caster_radius}"/>
                </inertial>
            </link>
            <joint name="base_to_${prefix}_caster" type="fixed">
                <parent link="base_link"/>
                <child link="${prefix}_caster"/>
                <origin xyz="${position}" rpy="0 0 0"/>
            </joint>
            <gazebo reference="${prefix}_caster">
                <mu1 value="0.0"/>
                <mu2 value="0.0"/>
            </gazebo>
        </xacro:macro>
        <xacro:caster prefix="front" position="0.08 0 ${caster_radius + 0.001}"/>
        <xacro:caster prefix="rear" position="-0.08 0 ${caster_radius + 0.001}"/>

    </xacro:macro>
</robot>
